# Site settings
title: Girish Varma
email: girishrv@tifr.res.in
description: > # this means to ignore newlines until "baseurl:"
  Home page of Girish Varma
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://geevi.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

